GET http://localhost:3001/rickandmorty/fav
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Imx1aXMiLCJpYXQiOjE2Nzk3NjI0OTcsImV4cCI6MTY4MDM2NzI5N30.i3C6xZqqd9E8NqDlwswB0DGyPI-c6GP4mL_LEQJ1Zz4